-- =============================================================================
-- 001_foundation.sql — extensions, shared helpers, identity and authentication
-- =============================================================================
-- Conventions used by every migration in this project:
--
--   * Primary keys are uuid, generated by the database (gen_random_uuid()).
--   * Money is BIGINT in MINOR UNITS (paisa). Never numeric, never float:
--     integers are exact, and a finance app that disagrees with the user's own
--     arithmetic by one paisa loses their trust.
--   * Every timestamp is timestamptz. A naive timestamp plus a user in another
--     timezone is a whole category of "my daily total is wrong" bug reports.
--   * Every user-owned table carries user_id with ON DELETE CASCADE, so an
--     account deletion really removes the data (a legal requirement, not a
--     nice-to-have).
--   * Enumerated values are varchar + CHECK, not Postgres ENUM types. Adding a
--     value to a CHECK is a cheap ALTER; changing an ENUM in a live database is
--     not, and this product will keep adding user types and plan codes.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid(), digest()
CREATE EXTENSION IF NOT EXISTS citext;     -- case-insensitive email/username
CREATE EXTENSION IF NOT EXISTS pg_trgm;    -- fast ILIKE search on notes/titles

-- -----------------------------------------------------------------------------
-- Shared trigger: keep updated_at honest.
-- Doing this in the database rather than in Go means a manual psql UPDATE, a
-- background job and an API call all leave a correct timestamp behind.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =============================================================================
-- users
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- identity -----------------------------------------------------------
    name                varchar(100) NOT NULL,
    username            citext UNIQUE,
    email               citext UNIQUE,
    phone               varchar(20)  NOT NULL UNIQUE,
    password_hash       text         NOT NULL,
    avatar_path         text,

    -- profile ------------------------------------------------------------
    -- user_type drives which dashboard and which AI prompts the user gets.
    user_type           varchar(20)  NOT NULL DEFAULT 'personal'
        CHECK (user_type IN ('personal','student','job_holder','business','freelancer','family')),
    role                varchar(20)  NOT NULL DEFAULT 'user'
        CHECK (role IN ('user','admin','support')),
    status              varchar(20)  NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','suspended','deleted')),

    locale              varchar(5)   NOT NULL DEFAULT 'bn' CHECK (locale IN ('bn','en')),
    currency            char(3)      NOT NULL DEFAULT 'BDT',
    timezone            varchar(64)  NOT NULL DEFAULT 'Asia/Dhaka',

    -- money cycle --------------------------------------------------------
    -- monthly_income is the planning figure the user enters at onboarding.
    -- Actual income rows live in the incomes table; this is the budget baseline.
    monthly_income      bigint       NOT NULL DEFAULT 0 CHECK (monthly_income >= 0),
    -- A salaried user's "month" often starts on payday, not on the 1st. Every
    -- dashboard and monthly report honours this.
    month_start_day     smallint     NOT NULL DEFAULT 1
        CHECK (month_start_day BETWEEN 1 AND 28),

    -- verification -------------------------------------------------------
    phone_verified      boolean      NOT NULL DEFAULT false,
    phone_verified_at   timestamptz,
    email_verified      boolean      NOT NULL DEFAULT false,
    email_verified_at   timestamptz,

    -- onboarding ---------------------------------------------------------
    onboarding_step     varchar(30)  NOT NULL DEFAULT 'profile'
        CHECK (onboarding_step IN ('profile','income','categories','budget','done')),
    onboarded_at        timestamptz,

    -- billing snapshot ---------------------------------------------------
    -- Denormalised from the subscriptions table so the auth middleware can put
    -- the plan into the JWT without a second query on every single request.
    -- The subscriptions table remains the source of truth.
    plan_code           varchar(40)  NOT NULL DEFAULT 'free',
    plan_expires_at     timestamptz,

    -- security -----------------------------------------------------------
    failed_login_count  integer      NOT NULL DEFAULT 0,
    locked_until        timestamptz,
    password_changed_at timestamptz  NOT NULL DEFAULT now(),
    last_login_at       timestamptz,
    last_login_ip       inet,
    last_seen_at        timestamptz,

    -- soft delete: keeps historical analytics and financial records intact
    -- during the grace period before a hard purge.
    deleted_at          timestamptz,

    metadata            jsonb        NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT users_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT users_username_format CHECK (
        username IS NULL OR username ~ '^[a-z0-9][a-z0-9_.]{1,28}[a-z0-9]$'
    )
);

COMMENT ON COLUMN users.monthly_income  IS 'Planning baseline in paisa (BDT minor units).';
COMMENT ON COLUMN users.month_start_day IS 'Day of month the budget cycle starts; salary day for job holders.';
COMMENT ON COLUMN users.plan_code       IS 'Denormalised current plan; subscriptions table is the source of truth.';

-- Partial index: almost every query filters out deleted accounts, and keeping
-- them out of the index makes it smaller and the plans better.
CREATE INDEX IF NOT EXISTS users_active_idx      ON users (created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS users_phone_idx       ON users (phone)           WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS users_plan_idx        ON users (plan_code, plan_expires_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS users_status_idx      ON users (status)          WHERE deleted_at IS NULL;
-- Trigram index powers admin user search (ILIKE '%name%') without a seq scan.
CREATE INDEX IF NOT EXISTS users_name_trgm_idx   ON users USING gin (name gin_trgm_ops);

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- =============================================================================
-- sessions — refresh tokens, one row per signed-in device
-- =============================================================================
-- Only the SHA-256 of the refresh token is stored. A database dump therefore
-- does not let an attacker impersonate anybody.
--
-- family_id implements refresh-token rotation with reuse detection: every
-- refresh issues a new token in the same family and revokes the old one. If a
-- token that was already used is presented again, the token was stolen — and
-- the whole family is revoked, signing that device out everywhere.
-- =============================================================================
CREATE TABLE IF NOT EXISTS sessions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    family_id      uuid        NOT NULL DEFAULT gen_random_uuid(),
    token_hash     char(64)    NOT NULL UNIQUE,

    device_name    varchar(120),
    user_agent     text,
    ip             inet,

    expires_at     timestamptz NOT NULL,
    last_used_at   timestamptz NOT NULL DEFAULT now(),
    revoked_at     timestamptz,
    revoked_reason varchar(40)
        CHECK (revoked_reason IS NULL OR revoked_reason IN
              ('logout','rotated','reuse_detected','password_changed','admin','expired','device_limit')),

    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sessions_user_active_idx ON sessions (user_id, expires_at DESC)
    WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS sessions_family_idx      ON sessions (family_id);
CREATE INDEX IF NOT EXISTS sessions_cleanup_idx     ON sessions (expires_at);


-- =============================================================================
-- otp_codes — phone verification, login and password reset
-- =============================================================================
CREATE TABLE IF NOT EXISTS otp_codes (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid REFERENCES users(id) ON DELETE CASCADE,
    phone         varchar(20)  NOT NULL,
    purpose       varchar(30)  NOT NULL
        CHECK (purpose IN ('register','login','reset_password','change_phone','change_email')),

    -- Only the hash is stored, for the same reason as refresh tokens.
    code_hash     char(64)     NOT NULL,

    -- Attempts are counted per code, so guessing a 6-digit OTP is bounded to a
    -- handful of tries rather than the full 1,000,000 keyspace.
    attempts      smallint     NOT NULL DEFAULT 0,
    max_attempts  smallint     NOT NULL DEFAULT 5,

    expires_at    timestamptz  NOT NULL,
    consumed_at   timestamptz,
    request_ip    inet,
    created_at    timestamptz  NOT NULL DEFAULT now()
);

-- Supports both the rate-limit count and the "latest live code" lookup.
CREATE INDEX IF NOT EXISTS otp_codes_lookup_idx  ON otp_codes (phone, purpose, created_at DESC);
CREATE INDEX IF NOT EXISTS otp_codes_cleanup_idx ON otp_codes (expires_at);


-- =============================================================================
-- login_attempts — append-only security audit
-- =============================================================================
-- Enforcement uses users.locked_until (one indexed read). This table exists so
-- that "which IP tried 400 phone numbers last night?" is answerable.
-- =============================================================================
CREATE TABLE IF NOT EXISTS login_attempts (
    id         bigserial PRIMARY KEY,
    identifier varchar(255) NOT NULL,
    user_id    uuid REFERENCES users(id) ON DELETE SET NULL,
    success    boolean      NOT NULL DEFAULT false,
    reason     varchar(40),
    ip         inet,
    user_agent text,
    created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS login_attempts_identifier_idx ON login_attempts (identifier, created_at DESC);
CREATE INDEX IF NOT EXISTS login_attempts_ip_idx         ON login_attempts (ip, created_at DESC);


-- =============================================================================
-- audit_logs — who changed what
-- =============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id          bigserial PRIMARY KEY,
    user_id     uuid REFERENCES users(id) ON DELETE SET NULL,
    actor_role  varchar(20),
    action      varchar(60)  NOT NULL,     -- 'expense.deleted', 'subscription.purchased'
    entity_type varchar(40),
    entity_id   uuid,
    request_id  varchar(64),
    ip          inet,
    user_agent  text,
    changes     jsonb        NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_logs_user_idx   ON audit_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_action_idx ON audit_logs (action, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON audit_logs (entity_type, entity_id);


-- =============================================================================
-- idempotency_keys — make money endpoints safe to retry
-- =============================================================================
-- A mobile client on a flaky network WILL retry a purchase request. Without
-- this table the retry charges twice. With it, the second request replays the
-- first response.
-- =============================================================================
CREATE TABLE IF NOT EXISTS idempotency_keys (
    key           varchar(120) NOT NULL,
    user_id       uuid         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint      varchar(120) NOT NULL,
    request_hash  char(64)     NOT NULL,
    status        varchar(20)  NOT NULL DEFAULT 'in_progress'
        CHECK (status IN ('in_progress','completed','failed')),
    status_code   integer,
    response_body jsonb,
    expires_at    timestamptz  NOT NULL DEFAULT now() + interval '24 hours',
    created_at    timestamptz  NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, key)
);

CREATE INDEX IF NOT EXISTS idempotency_cleanup_idx ON idempotency_keys (expires_at);
